# Generated by Django 2.0.6 on 2018-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('bug_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=8)),
            ],
        ),
    ]
